version: '3.2'
services:

  mysql:
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysq
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: rut3sql
       MYSQL_DATABASE: crawler_memed
       MYSQL_USER: drpediu
       MYSQL_PASSWORD: DrP3d1u
  
  api:
    build:
     context: .
     dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html:rw
    env_file: .env
    ports:
      - "8001:8001"
    links:
      - mysql
    environment:
      TZ: America/Sao_Paulo
      LANG: pt_BR.UTF-8
      LANGUAGE: pt_BR.UTF-8
      LC_CTYPE: pt_BR.UTF-8
      LC_ALL: pt_BR.UTF-8
      LC_TIME: pt_BR.UTF-8

volumes:
  data:
